services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test-drive-scheduler
      POSTGRES_USER: bananas
      POSTGRES_PASSWORD: strawberries
  scheduler-service:
    container_name: scheduler-service
    build:
      context: .
      dockerfile: ./apps/backend/scheduler-service/Dockerfile
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: bananas
      DATABASE_PASSWORD: strawberries
      DATABASE_NAME: test-drive-scheduler
    ports:
      - '3000:3000'
    restart: on-failure
    depends_on:
      - db
  scheduler-webapp:
    container_name: scheduler-webapp
    build:
      context: .
      dockerfile: ./apps/frontend/scheduler-webapp/Dockerfile
    ports:
      - '4200:80'
    restart: on-failure
    depends_on:
      - scheduler-service
networks:
  default:
    name: test-drive-scheduler
    driver: bridge
