services:
  postgres-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: test-drive-scheduler
      POSTGRES_USER: bananas
      POSTGRES_PASSWORD: strawberries
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: testdrive@example.com
      PGADMIN_DEFAULT_PASSWORD: strawberries
    volumes:
      - pgadmin-data:/var/lib/pgadmin
networks:
  default:
    name: test-drive-scheduler
    driver: bridge

volumes:
  postgres-db:
    driver: local
  pgadmin-data:
    driver: local
