services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: test-drive-scheduler
      POSTGRES_USER: bananas
      POSTGRES_PASSWORD: strawberries

networks:
  default:
    name: test-drive-scheduler
    driver: bridge
